// Auto-generated by WAE — Nimbus
// Page: Features (/features)

import Navbar from '@/components/navbar';
import PageHeader from '@/components/page-header';
import ContentGrid from '@/components/content-grid';
import Faq from '@/components/faq';
import FooterSimple from '@/components/footer-simple';

export default function FeaturesPage() {
  return (
    <>
    <main role="main">
      <Navbar
        maxWidth="container"
        alignment="space-between"
        sticky={true}
        transparent={true}
        ctaButton={true}
        brand="Nimbus"
        links={[{"label":"Features","href":"/features"},{"label":"Contact","href":"/contact"}]}
        ctaText="Get Started"
      />
      <PageHeader
        align="center"
        title="Features"
      />
      <ContentGrid
        columns={4}
        gap="small"
        responsive={true}
        headline="What We Offer"
        subtitle="Everything you need to succeed."
        items={[{"title":"Nimbus Extract","description":"Turn PDFs, invoices and contracts into clean structured data."},{"title":"Nimbus Summarize","description":"Concise summaries of long documents, tuned to the questions your team asks."},{"title":"Nimbus Route","description":"Route each document to the right person or system without rules that break."}]}
      />
      <Faq
        style="accordion"
        allowMultiple={false}
        headline="Frequently Asked Questions"
        subtitle="Answers to common questions."
        faqs={[{"question":"How is my data kept secure?","answer":"Nimbus is SOC 2 Type II compliant, encrypts data in transit and at rest, and never uses your documents to train models."},{"question":"Can Nimbus connect to our existing stack?","answer":"Yes — REST APIs, webhooks and native integrations make it easy to route structured output into your tools."}]}
      />
      <FooterSimple
        showLinks={true}
        showSocial={false}
        layout="centered"
        description="Nimbus is an AI SaaS platform that extracts, summarizes and routes unstructured documents into your existing workflows."
        links={[{"title":"Pages","items":[{"label":"Features","url":"/features"},{"label":"Contact","url":"/contact"}]},{"title":"Products","items":[{"label":"Nimbus Extract"},{"label":"Nimbus Summarize"},{"label":"Nimbus Route"}]},{"title":"Offices","items":[{"label":"San Francisco, USA","url":"/contact"},{"label":"Lisbon, Portugal","url":"/contact"}]},{"title":"Contact","items":[{"label":"hello@nimbus.example","url":"mailto:hello@nimbus.example"}]}]}
        social={[{"platform":"linkedin","url":"https://linkedin.com/company/nimbus"}]}
        copyright="2026 Nimbus"
      />
    </main>
<script
      type="application/ld+json"
      dangerouslySetInnerHTML={{ __html: "{\"@context\":\"https://schema.org\",\"@type\":\"WebPage\",\"name\":\"features | AI Platform\",\"url\":\"/features\"}" }}
    />
    </>
  );
}

// Per-page SEO metadata (evidence-first, projected by the Specification layer).
export { metadata } from './metadata';
