// Auto-generated by WAE — Nimbus
// Page: Contact (/contact)

import Navbar from '@/components/navbar';
import PageHeader from '@/components/page-header';
import ContactForm from '@/components/contact-form';
import FooterSimple from '@/components/footer-simple';

export default function ContactPage() {
  return (
    <>
    <main role="main">
      <Navbar
        maxWidth="container"
        alignment="space-between"
        sticky={true}
        transparent={true}
        ctaButton={true}
        brand="Nimbus"
        links={[{"label":"Features","href":"/features"},{"label":"Contact","href":"/contact"}]}
        ctaText="Get Started"
      />
      <PageHeader
        align="center"
        title="Contact"
      />
      <ContactForm
        fields={["name","email","phone","company","message"]}
        showMap={false}
        layout="stacked"
        headline="Get in Touch"
        subtitle="We would love to hear from you."
        submitText="Send Message"
        email="hello@nimbus.example"
        address="San Francisco, CA, USA"
      />
      <FooterSimple
        showLinks={true}
        showSocial={false}
        layout="centered"
        description="Nimbus is an AI SaaS platform that extracts, summarizes and routes unstructured documents into your existing workflows."
        links={[{"title":"Pages","items":[{"label":"Features","url":"/features"},{"label":"Contact","url":"/contact"}]},{"title":"Products","items":[{"label":"Nimbus Extract"},{"label":"Nimbus Summarize"},{"label":"Nimbus Route"}]},{"title":"Offices","items":[{"label":"San Francisco, USA","url":"/contact"},{"label":"Lisbon, Portugal","url":"/contact"}]},{"title":"Contact","items":[{"label":"hello@nimbus.example","url":"mailto:hello@nimbus.example"}]}]}
        social={[{"platform":"linkedin","url":"https://linkedin.com/company/nimbus"}]}
        copyright="2026 Nimbus"
      />
    </main>
<script
      type="application/ld+json"
      dangerouslySetInnerHTML={{ __html: "{\"@context\":\"https://schema.org\",\"@type\":\"WebPage\",\"name\":\"contact | AI Platform\",\"url\":\"/contact\"}" }}
    />
    </>
  );
}

// Per-page SEO metadata (evidence-first, projected by the Specification layer).
export { metadata } from './metadata';
