// Auto-generated by WAE — Nimbus
import type { Metadata, Viewport } from 'next';
import './globals.css';

export const metadata: Metadata = {
  title: 'Nimbus',
  description: 'Nimbus is an AI SaaS platform that extracts, summarizes and routes unstructured documents into your existing workflows.',
  openGraph: {
    title: 'Nimbus',
    description: 'Nimbus is an AI SaaS platform that extracts, summarizes and routes unstructured documents into your existing workflows.',
    type: 'website',
  },
  twitter: {
    card: 'summary_large_image',
    title: 'Nimbus',
    description: 'Nimbus is an AI SaaS platform that extracts, summarizes and routes unstructured documents into your existing workflows.',
  },
};

export const viewport: Viewport = {
  themeColor: '#4f46e5',
  width: 'device-width',
  initialScale: 1,
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="anonymous" />
        <link href="https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600;700;800&display=swap" rel="stylesheet" />
      </head>
      <body className="bg-background text-text antialiased">{children}</body>
    </html>
  );
}
