// Auto-generated by WAE — Nimbus
// Page: Home (/)

import VisualBackground from '@/components/visual-background';
import Navbar from '@/components/navbar';
import HeroCentered from '@/components/hero-centered';
import PricingTable from '@/components/pricing-table';
import FeatureGrid from '@/components/feature-grid';
import StatsBar from '@/components/stats-bar';
import CtaBanner from '@/components/cta-banner';
import FooterMultiColumn from '@/components/footer-multi-column';

export default function HomePage() {
  return (
    <>
    <main role="main">
      <VisualBackground
        capabilities={["procedural-background","image-preview","shader-background"]}
        title="Nimbus"
      />
      <Navbar
        maxWidth="container"
        alignment="space-between"
        sticky={true}
        transparent={true}
        ctaButton={true}
        brand="Nimbus"
        links={[{"label":"Features","href":"/features"},{"label":"Contact","href":"/contact"}]}
        ctaText="Get Started"
      />
      <HeroCentered
        textAlign="center"
        headline="Intelligent document automation for modern teams"
        subtitle="Nimbus is an AI SaaS platform that extracts, summarizes and routes unstructured documents into your existing workflows."
        metrics={[{"value":"2.4M","label":"Documents processed monthly"},{"value":"99.2","label":"Average accuracy"}]}
        ctaText="Get Started"
        ctaLink="/contact"
      />
      <PricingTable
        tiers={3}
        showFeatures={true}
        billing="monthly"
        highlightedTier="middle"
        headline="Simple, Transparent Pricing"
        subtitle="Choose the plan that fits your needs."
        pricing={[{"name":"Starter","price":"$0","description":"For trying Nimbus with your own documents.","features":["200 pages / month","Extract + Summarize","Community support"]},{"name":"Growth","price":"$99","description":"For teams that need reliable volume.","features":["10,000 pages / month","All modules","Priority support"]},{"name":"Enterprise","price":"Custom","description":"For scale, security and control.","features":["Unlimited pages","SOC 2 + SSO/SAML","Dedicated manager"]}]}
      />
      <FeatureGrid
        columns={4}
        iconStyle="outlined"
        cardStyle="bordered"
        headline="Key Features"
        subtitle="Built to help you move faster."
        features={[{"title":"Nimbus Extract","description":"Turn PDFs, invoices and contracts into clean structured data."},{"title":"Nimbus Summarize","description":"Concise summaries of long documents, tuned to the questions your team asks."},{"title":"Nimbus Route","description":"Route each document to the right person or system without rules that break."}]}
      />
      <StatsBar
        headline="Our Impact"
        subtitle="Numbers that speak for themselves."
        stats={[{"label":"Documents processed monthly","value":"2.4M"},{"label":"Average accuracy","value":"99.2"},{"label":"Hours saved per week","value":"18"}]}
      />
      <CtaBanner
        buttonStyle="primary"
        showDescription={true}
        background="gradient"
        backgroundImage={true}
        headline="Ready to drive product signups and conversions; promote an AI platform?"
        ctaText="Get Started"
        ctaLink="/contact"
        testimonial={{"quote":"Nimbus cut our invoice processing time from hours to minutes. The accuracy is genuinely impressive.","author":"Melisa Ortega","company":"Lumen Retail"}}
        layout="split"
        stats={[{"value":"2.4M","label":"Documents processed monthly"},{"value":"99.2","label":"Average accuracy"},{"value":"18","label":"Hours saved per week"}]}
      />
      <FooterMultiColumn
        columns={4}
        showSocial={true}
        showNewsletter={false}
        description="Nimbus is an AI SaaS platform that extracts, summarizes and routes unstructured documents into your existing workflows."
        links={[{"title":"Pages","items":[{"label":"Features","url":"/features"},{"label":"Contact","url":"/contact"}]},{"title":"Products","items":[{"label":"Nimbus Extract"},{"label":"Nimbus Summarize"},{"label":"Nimbus Route"}]},{"title":"Offices","items":[{"label":"San Francisco, USA","url":"/contact"},{"label":"Lisbon, Portugal","url":"/contact"}]},{"title":"Contact","items":[{"label":"hello@nimbus.example","url":"mailto:hello@nimbus.example"}]}]}
        social={[{"platform":"linkedin","url":"https://linkedin.com/company/nimbus"}]}
        copyright="2026 Nimbus"
      />
    </main>
<script
      type="application/ld+json"
      dangerouslySetInnerHTML={{ __html: "{\"@context\":\"https://schema.org\",\"@type\":\"WebPage\",\"name\":\"Home | AI Platform\",\"url\":\"/\"}" }}
    />
    </>
  );
}

// Per-page SEO metadata (evidence-first, projected by the Specification layer).
export { metadata } from './metadata';
