// Auto-generated by WAE — Nimbus
// Component: contact-form (detailed)
"use client";

import { useState, type FormEvent } from 'react';

export default function ContactForm({
  headline = "Get in Touch",
  subtitle = "We would love to hear from you.",
  showPhone = true,
  showAddress = true,
  phone = "",
  address = "San Francisco, CA, USA",
  email = "hello@nimbus.example",
  submitText = "Send Message",
  hours = [],
  fields = ["name","email","phone","company","message"],
  showMap = false,
  layout = "stacked",
}: {
  headline?: string;
  subtitle?: string;
  showPhone?: boolean;
  showAddress?: boolean;
  phone?: string;
  address?: string;
  email?: string;
  submitText?: string;
  hours?: string[];
  fields?: string[];
  showMap?: boolean;
  layout?: string;
}) {
  const [formState, setFormState] = useState({ name: '', email: '', message: '' });
  const [submitted, setSubmitted] = useState(false);

  const handleSubmit = (e: FormEvent<HTMLFormElement>) => {
    e.preventDefault();
    setSubmitted(true);
  };

  return (
    <section className="py-20 sm:py-24 lg:py-32 bg-background" aria-label="Contact">
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
        <div className="max-w-2xl mx-auto text-center mb-16">
          <h2 className="text-3xl sm:text-4xl lg:text-5xl font-bold tracking-tight text-secondary">{headline}</h2>
          <p className="mt-4 text-lg text-text-secondary">{subtitle}</p>
        </div>
        <div className="max-w-2xl mx-auto">
          {submitted ? (
            <div className="text-center p-12 rounded-2xl bg-surface border border-text-secondary/15">
              <svg className="w-16 h-16 text-green-500 mx-auto mb-4" fill="none" viewBox="0 0 24 24" stroke="currentColor" aria-hidden="true">
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9 12l2 2 4-4m6 2a9 9 0 11-18 0 9 9 0 0118 0z" />
              </svg>
              <h3 className="text-2xl font-bold text-secondary mb-2">Message sent!</h3>
              <p className="text-text-secondary">We will get back to you within 24 hours.</p>
            </div>
          ) : (
            <form onSubmit={handleSubmit} className="space-y-6">
              {fields.includes('name') && (
              <div>
                <label htmlFor="name" className="block text-sm font-medium text-secondary mb-1">Name</label>
                <input
                  id="name"
                  type="text"
                  required
                  value={formState.name}
                  onChange={(e) => setFormState({ ...formState, name: e.target.value })}
                  className="w-full px-4 py-3 rounded-xl border border-text-secondary/20 focus:ring-2 focus:ring-primary focus:border-primary outline-none transition-all duration-200"
                  placeholder="Your name"
                />
              </div>
              )}
              {fields.includes('email') && (
              <div>
                <label htmlFor="email" className="block text-sm font-medium text-secondary mb-1">Email</label>
                <input
                  id="email"
                  type="email"
                  required
                  value={formState.email}
                  onChange={(e) => setFormState({ ...formState, email: e.target.value })}
                  className="w-full px-4 py-3 rounded-xl border border-text-secondary/20 focus:ring-2 focus:ring-primary focus:border-primary outline-none transition-all duration-200"
                  placeholder="you@example.com"
                />
              </div>
              )}
              {fields.includes('message') && (
              <div>
                <label htmlFor="message" className="block text-sm font-medium text-secondary mb-1">Message</label>
                <textarea
                  id="message"
                  required
                  rows={5}
                  value={formState.message}
                  onChange={(e) => setFormState({ ...formState, message: e.target.value })}
                  className="w-full px-4 py-3 rounded-xl border border-text-secondary/20 focus:ring-2 focus:ring-primary focus:border-primary outline-none transition-all duration-200 resize-none"
                  placeholder="Your message..."
                />
              </div>
              )}
              <button
                type="submit"
                className="w-full px-8 py-3.5 text-base font-semibold text-white bg-wae-gradient-primary rounded-xl hover:opacity-95 transition-all duration-200 shadow-lift focus:outline-none focus:ring-2 focus:ring-primary focus:ring-offset-2"
              >
                {submitText}
              </button>
            </form>
          )}
          {(showPhone || showAddress || (hours && hours.length > 0)) && (
            <div className="mt-12 grid grid-cols-1 sm:grid-cols-2 gap-6">
              {showPhone && phone && (
                <div className="flex items-center gap-4 p-6 rounded-xl bg-surface border border-text-secondary/15">
                  <div className="w-12 h-12 rounded-xl bg-accent/15 flex items-center justify-center flex-shrink-0">
                    <svg className="w-6 h-6 text-accent" fill="none" viewBox="0 0 24 24" stroke="currentColor" aria-hidden="true">
                      <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M3 5a2 2 0 012-2h3.28a1 1 0 01.948.684l1.498 4.493a1 1 0 01-.502 1.21l-2.257 1.13a11.042 11.042 0 005.516 5.516l1.13-2.257a1 1 0 011.21-.502l4.493 1.498a1 1 0 01.684.949V19a2 2 0 01-2 2h-1C9.716 21 3 14.284 3 6V5z" />
                    </svg>
                  </div>
                  <div>
                    <div className="text-sm font-medium text-secondary">Phone</div>
                    <div className="text-sm text-text-secondary">{phone}</div>
                  </div>
                </div>
              )}
              {showAddress && address && (
                <div className="flex items-center gap-4 p-6 rounded-xl bg-surface border border-text-secondary/15">
                  <div className="w-12 h-12 rounded-xl bg-accent/15 flex items-center justify-center flex-shrink-0">
                    <svg className="w-6 h-6 text-accent" fill="none" viewBox="0 0 24 24" stroke="currentColor" aria-hidden="true">
                      <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M17.657 16.657L13.414 20.9a1.998 1.998 0 01-2.827 0l-4.244-4.243a8 8 0 1111.314 0z" />
                      <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M15 11a3 3 0 11-6 0 3 3 0 016 0z" />
                    </svg>
                  </div>
                  <div>
                    <div className="text-sm font-medium text-secondary">Address</div>
                    <div className="text-sm text-text-secondary">{address}</div>
                  </div>
                </div>
              )}
              {hours && hours.length > 0 && (
                <div className="flex items-center gap-4 p-6 rounded-xl bg-surface border border-text-secondary/15">
                  <div className="w-12 h-12 rounded-xl bg-accent/15 flex items-center justify-center flex-shrink-0">
                    <svg className="w-6 h-6 text-accent" fill="none" viewBox="0 0 24 24" stroke="currentColor" aria-hidden="true">
                      <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 8v4l3 3m6-3a9 9 0 11-18 0 9 9 0 0118 0z" />
                    </svg>
                  </div>
                  <div>
                    <div className="text-sm font-medium text-secondary">Business hours</div>
                    <div className="text-sm text-text-secondary">{hours.join(' · ')}</div>
                  </div>
                </div>
              )}
            </div>
          )}
        </div>
      </div>
    </section>
  );
}
