// Auto-generated by WAE — Nimbus
// Component: cta-banner (with-image)

export default function CtaBanner({
  buttonStyle = "primary",
  showDescription = true,
  background = "gradient",
  backgroundImage = true,
  layout = "split",
  headline = "Ready to drive product signups and conversions; promote an AI platform?",
  subtitle = "",
  ctaText = "Get Started",
  ctaLink = "/contact",
  secondaryCtaText = "",
  secondaryCtaLink = "",
  stats = [{"value":"2.4M","label":"Documents processed monthly"},{"value":"99.2","label":"Average accuracy"},{"value":"18","label":"Hours saved per week"}],
  testimonial = {"quote":"Nimbus cut our invoice processing time from hours to minutes. The accuracy is genuinely impressive.","author":"Melisa Ortega","company":"Lumen Retail"},
}: {
  buttonStyle?: string;
  showDescription?: boolean;
  background?: string;
  backgroundImage?: boolean;
  layout?: string;
  headline?: string;
  subtitle?: string;
  ctaText?: string;
  ctaLink?: string;
  secondaryCtaText?: string;
  secondaryCtaLink?: string;
  stats?: Array<{ value: string; label: string }>;
  testimonial?: { quote?: string; author?: string; company?: string } | null;
}) {
  return (
    <section id="cta" className={`relative overflow-hidden `} aria-label="Call to action">
      <div className={`absolute inset-0 bg-wae-gradient-primary`} aria-hidden="true" />
      {backgroundImage ? (
      <div className="absolute inset-0 opacity-20" style={{ backgroundImage: 'radial-gradient(circle at 20% 50%, rgba(255,255,255,0.25) 0, transparent 40%), radial-gradient(circle at 80% 20%, rgba(255,255,255,0.15) 0, transparent 40%)' }} aria-hidden="true" />
      ) : null}
      <div className="relative max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-20 sm:py-24 lg:py-28">
        <div className={`flex flex-col lg:flex-row lg:items-center lg:justify-between gap-10`}>
          <div className={`max-w-xl text-left`}>
            {testimonial && testimonial.quote ? (
              <blockquote className="mb-6">
                <p className="text-lg text-background/90 italic leading-relaxed">“{testimonial.quote}”</p>
                <footer className="mt-2 text-sm text-background/70">
                  {testimonial.author}{testimonial.company ? `, ${testimonial.company}` : ''}
                </footer>
              </blockquote>
            ) : null}
            <h2 className="text-3xl sm:text-4xl lg:text-5xl font-bold tracking-tight text-background">{headline}</h2>
            {showDescription && <p className="mt-6 text-lg sm:text-xl text-background/80 leading-relaxed">{subtitle}</p>}
            <div className={`mt-10 flex flex-wrap gap-4 `}>
              <a href={ctaLink} className="inline-flex items-center px-8 py-3.5 text-base font-semibold text-secondary bg-surface rounded-xl hover:bg-surface/90 transition-all duration-200 shadow-lift focus:outline-none focus:ring-2 focus:ring-background focus:ring-offset-2 focus:ring-offset-primary">
                {ctaText}
                <svg className="ml-2 w-5 h-5" fill="none" viewBox="0 0 24 24" stroke="currentColor" aria-hidden="true">
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M13 7l5 5m0 0l-5 5m5-5H6" />
                </svg>
              </a>
              {secondaryCtaLink && (
                <a href={secondaryCtaLink} className="inline-flex items-center px-8 py-3.5 text-base font-semibold text-background border-2 border-background/40 rounded-xl hover:bg-background/10 transition-all duration-200 focus:outline-none focus:ring-2 focus:ring-background focus:ring-offset-2 focus:ring-offset-primary">
                  {secondaryCtaText}
                </a>
              )}
            </div>
          </div>
          <div className={`grid grid-cols-2 gap-6 w-full lg:w-auto`}>
            <div className="text-center">
              <div className="text-3xl sm:text-4xl font-bold text-background">2.4M</div>
              <div className="mt-1 text-sm text-background/70">Documents processed monthly</div>
            </div><div className="text-center">
              <div className="text-3xl sm:text-4xl font-bold text-background">99.2</div>
              <div className="mt-1 text-sm text-background/70">Average accuracy</div>
            </div><div className="text-center">
              <div className="text-3xl sm:text-4xl font-bold text-background">18</div>
              <div className="mt-1 text-sm text-background/70">Hours saved per week</div>
            </div>
          </div>
        </div>
      </div>
    </section>
  );
}
