// Auto-generated by WAE — Nimbus
// Component: faq (accordion)
"use client";

import { useState } from 'react';

export default function Faq({
  headline = "Frequently Asked Questions",
  subtitle = "Answers to common questions.",
  columns = 1,
  faqs = [{"question":"How is my data kept secure?","answer":"Nimbus is SOC 2 Type II compliant, encrypts data in transit and at rest, and never uses your documents to train models."},{"question":"Can Nimbus connect to our existing stack?","answer":"Yes — REST APIs, webhooks and native integrations make it easy to route structured output into your tools."}],
  style = "accordion",
  allowMultiple = false,
}: {
  headline?: string;
  subtitle?: string;
  columns?: number;
  faqs?: Array<{ question: string; answer: string }>;
  items?: Array<{ question: string; answer: string }>;
  style?: string;
  allowMultiple?: boolean;
}) {
  const [openIndex, setOpenIndex] = useState<number | null>(null);
  const [openIndices, setOpenIndices] = useState<number[]>([]);

  const toggleFaq = (index: number) => {
    if (allowMultiple) {
      setOpenIndices((prev) =>
        prev.includes(index) ? prev.filter((i) => i !== index) : [...prev, index]
      );
    } else {
      setOpenIndex(openIndex === index ? null : index);
    }
  };

  const isOpen = (index: number) => {
    if (allowMultiple) {
      return openIndices.includes(index);
    }
    return openIndex === index;
  };

  return (
    <section className="py-20 sm:py-24 lg:py-32 bg-surface" aria-label="FAQ">
      <div className="max-w-3xl mx-auto px-4 sm:px-6 lg:px-8">
        <div className="text-center mb-16">
          <h2 className="text-3xl sm:text-4xl lg:text-5xl font-bold tracking-tight text-secondary">{headline}</h2>
          <p className="mt-4 text-lg text-text-secondary">{subtitle}</p>
        </div>
        <div className="space-y-4">
          {faqs.map((faq, index) => (
            <div key={index} className="rounded-2xl border border-text-secondary/15 overflow-hidden">
              <button
                type="button"
                onClick={() => toggleFaq(index)}
                className="w-full flex items-center justify-between px-6 py-4 text-left bg-surface hover:bg-background transition-colors duration-200"
                aria-expanded={isOpen(index)}
              >
                <span className="text-base font-semibold text-secondary pr-4">{faq.question}</span>
                <svg
                  className={'w-5 h-5 text-text-secondary flex-shrink-0 transition-transform duration-200 ' + (isOpen(index) ? 'rotate-180' : '')}
                  fill="none" viewBox="0 0 24 24" stroke="currentColor" aria-hidden="true"
                >
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M19 9l-7 7-7-7" />
                </svg>
              </button>
              {isOpen(index) && (
                <div className="px-6 pb-4">
                  <p className="text-text-secondary leading-relaxed">{faq.answer}</p>
                </div>
              )}
            </div>
          ))}
        </div>
      </div>
    </section>
  );
}
