// Auto-generated by WAE — Nimbus
// Component: feature-grid (3-col)

export default function FeatureGrid({
  columns = 4,
  iconStyle = "outlined",
  cardStyle = "bordered",
  headline = "Key Features",
  subtitle = "Built to help you move faster.",
  features = [{"title":"Nimbus Extract","description":"Turn PDFs, invoices and contracts into clean structured data."},{"title":"Nimbus Summarize","description":"Concise summaries of long documents, tuned to the questions your team asks."},{"title":"Nimbus Route","description":"Route each document to the right person or system without rules that break."}],
  media = [],
}: {
  columns?: number;
  iconStyle?: string;
  cardStyle?: string;
  headline?: string;
  subtitle?: string;
  features?: Array<{ title: string; description?: string; icon?: string }>;
  media?: Array<string | { url: string; alt?: string; width?: number; height?: number; role?: string }>;
}) {
  const icons: Record<string, string> = {
    chart: "M9 19v-6a2 2 0 00-2-2H5a2 2 0 00-2 2v6a2 2 0 002 2h2a2 2 0 002-2zm0 0V9a2 2 0 012-2h2a2 2 0 012 2v10m-6 0a2 2 0 002 2h2a2 2 0 002-2m0 0V5a2 2 0 012-2h2a2 2 0 012 2v14a2 2 0 01-2 2h-2a2 2 0 01-2-2z",
    automation: "M4 4v5h.582m15.356 2A8.001 8.001 0 004.582 9m0 0H9m11 11v-5h-.581m0 0a8.003 8.003 0 01-15.357-2m15.357 2H15",
    team: "M12 4.354a4 4 0 110 5.292M15 21H3v-1a6 6 0 0112 0v1zm0 0h6v-1a6 6 0 00-9-5.197m13.5-9a2.5 2.5 0 11-5 0 2.5 2.5 0 015 0z",
    security: "M9 12l2 2 4-4m5.618-4.016A11.955 11.955 0 0112 2.944a11.955 11.955 0 01-8.618 3.04A12.02 12.02 0 003 9c0 5.591 3.824 10.29 9 11.622 5.176-1.332 9-6.03 9-11.622 0-1.042-.133-2.052-.382-3.016z",
    api: "M8 9l3 3-3 3m5 0h3M5 20h14a2 2 0 002-2V6a2 2 0 00-2-2H5a2 2 0 00-2 2v12a2 2 0 002 2z",
    scale: "M4 8V4m0 0h4M4 4l5 5m11-1V4m0 0h-4m4 0l-5 5M4 16v4m0 0h4m-4 0l5-5m11 5l-5-5m5 5v-4m0 4h-4",
  };

  return (
    <section id="features" className="py-20 sm:py-24 lg:py-32 bg-background" aria-label="Features" data-wae-responsive="compact-table">
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
        
        <div className="max-w-2xl mx-auto text-center mb-16">
          <h2 className="text-3xl sm:text-4xl lg:text-5xl font-bold tracking-tight text-secondary">{headline}</h2>
          <p className="mt-4 text-lg text-text-secondary leading-relaxed">{subtitle}</p>
        </div>
        <div className={`grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3`}>
          {features.map((feature, index) => (
            <div key={index} className={`group relative p-6 lg:p-8 rounded-2xl bg-surface border border-text-secondary/15 hover:shadow-lg hover:border-text-secondary/20 transition-all duration-300`}>
              <div className={`inline-flex p-3 rounded-xl bg-accent/15 text-accent transition-colors duration-200`}>
                <svg className="w-6 h-6" fill="none" viewBox="0 0 24 24" stroke="currentColor" aria-hidden="true">
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.5} d={icons[feature.icon || 'chart'] || icons.chart} />
                </svg>
              </div>
              <h3 className="mt-4 text-lg font-semibold text-secondary">{feature.title}</h3>
              {feature.description ? <p className="mt-2 text-sm text-text-secondary leading-relaxed">{feature.description}</p> : null}
            </div>
          ))}
        </div>
      </div>
    </section>
  );
}
