// Auto-generated by WAE — Nimbus
// Component: hero-centered (with-image-right)

export default function HeroCentered({
  headline = "Intelligent document automation for modern teams",
  subtitle = "Nimbus is an AI SaaS platform that extracts, summarizes and routes unstructured documents into your existing workflows.",
  tagline = "",
  ctaText = "Get Started",
  ctaLink = "/contact",
  secondaryCtaText = "",
  secondaryCtaLink = "",
  ctaButtons = 1,
  showBadge = false,
  badgeText = "",
  highlight = "",
  metrics = [{"value":"2.4M","label":"Documents processed monthly"},{"value":"99.2","label":"Average accuracy"}],
  trustedBy = [],
  trustedByLabel = "Trusted by",
  maxWidth = 720,
  textAlign = "center",
  imagePosition = "bottom",
  minHeight = "80vh",
  contentWidth = 50,
  media = [],
  overlay = false,
}: {
  headline?: string;
  subtitle?: string;
  tagline?: string;
  ctaText?: string;
  ctaLink?: string;
  secondaryCtaText?: string;
  secondaryCtaLink?: string;
  ctaButtons?: number;
  showBadge?: boolean;
  badgeText?: string;
  highlight?: string;
  metrics?: Array<{ value: string; label: string }>;
  trustedBy?: string[];
  trustedByLabel?: string;
  maxWidth?: number;
  textAlign?: string;
  imagePosition?: string;
  minHeight?: string;
  contentWidth?: number;
  overlay?: boolean;
  media?: Array<string | { url: string; alt?: string; width?: number; height?: number; role?: string; type?: 'image' | 'video'; temporal?: { start: number; end: number }; poster?: string }>;
}) {
  const headlineNode = highlight && headline.includes(highlight) ? (
    <>
      {headline.slice(0, headline.lastIndexOf(highlight))}
      <span className="text-wae-gradient font-extrabold">{highlight}</span>
      {headline.slice(headline.lastIndexOf(highlight) + highlight.length)}
    </>
  ) : headline;
  const mediaSrc = media.length > 0 ? (typeof media[0] === "string" ? media[0] : media[0].url) : null;
  return (
    <section className="relative overflow-hidden bg-background" aria-label="Hero section">
      
      
      <div className="absolute inset-0 overflow-hidden" aria-hidden="true">
        

        
        
      </div>
      
      <div className={`relative max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-20 sm:py-24 lg:py-32 gap-10 lg:gap-16 flex flex-col justify-center ${false ? 'lg:flex-row lg:items-center' : (false ? 'items-center text-center' : 'items-center')}`}>
        <div className={`${false ? `w-full lg:w-[undefined%]` : 'max-w-[720px]'} ${textAlign === 'center' || false ? 'text-center items-center' : 'text-left items-start'} flex flex-col`}>
          
          <h1 className="font-heading text-5xl sm:text-6xl lg:text-7xl font-bold tracking-[-0.02em] text-text leading-[1.04] animate-fade-up">
            {headlineNode}
          </h1>
          {subtitle ? (
            <div className="mt-6 flex items-center gap-3 animate-fade-up" style={{ animationDelay: '90ms' }}>
              <span className="h-px w-10 bg-accent/60" aria-hidden="true" />
              <p className="text-base sm:text-lg font-medium text-secondary tracking-wide">
                {subtitle}
              </p>
            </div>
          ) : null}
          {tagline ? (
            <p className="mt-3 text-sm sm:text-base text-text-secondary/90 leading-7 max-w-[30ch] animate-fade-up" style={{ animationDelay: '180ms' }}>
              {tagline}
            </p>
          ) : null}
          {ctaLink ? (
          <div className="mt-10 flex flex-wrap gap-4 animate-fade-up" style={{ animationDelay: '260ms' }}>
            <a href={ctaLink} className="inline-flex items-center px-8 py-3.5 text-base font-semibold text-white bg-wae-gradient-primary rounded-xl hover:opacity-95 transition-all duration-200 shadow-card focus:outline-none focus:ring-2 focus:ring-primary focus:ring-offset-2">
              {ctaText}
              <svg className="ml-2 w-5 h-5" fill="none" viewBox="0 0 24 24" stroke="currentColor" aria-hidden="true">
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M13 7l5 5m0 0l-5 5m5-5H6" />
              </svg>
            </a>
            {ctaButtons >= 2 && (
              <a href={secondaryCtaLink} className="inline-flex items-center px-8 py-3.5 text-base font-semibold text-secondary bg-surface border-2 border-text-secondary/15 rounded-xl hover:border-primary/40 hover:bg-surface/80 transition-all duration-200 shadow-card focus:outline-none focus:ring-2 focus:ring-primary focus:ring-offset-2">
                {secondaryCtaText}
              </a>
            )}
          </div>
          ) : null}
          {trustedBy.length > 0 ? (
            <div className="mt-12 animate-fade-up" style={{ animationDelay: '340ms' }}>
              <p className="text-sm font-medium text-text-secondary">{trustedByLabel}</p>
              <div className="mt-3 flex flex-wrap gap-x-8 gap-y-2">
                {trustedBy.map((name) => (
                  <span key={name} className="text-base font-semibold text-text-secondary">{name}</span>
                ))}
              </div>
            </div>
          ) : null}
        </div>
        
      </div>
    </section>
  );
}
