// Auto-generated by WAE — Nimbus
// Component: navbar (transparent)

"use client";

import { useState } from "react";

export default function Navbar({
  sticky = true,
  transparent = true,
  ctaButton = true,
  ctaText = "Get Started",
  ctaLink = "#cta",
  maxWidth = "container",
  alignment = "space-between",
  brand = "Nimbus",
  logo = "",
  links = [{"label":"Features","href":"/features"},{"label":"Contact","href":"/contact"}],
}: {
  sticky?: boolean;
  transparent?: boolean;
  ctaButton?: boolean;
  ctaText?: string;
  ctaLink?: string;
  maxWidth?: string;
  alignment?: string;
  brand?: string;
  logo?: string;
  links?: Array<{ label: string; href: string }>;
}) {
  const navLinks = links;
  const [mobileOpen, setMobileOpen] = useState(false);

  return (
    <nav
      className={`sticky top-0 z-50 bg-background/20 backdrop-blur-md transition-all duration-300`}
      role="navigation"
      aria-label="Main navigation"
    >
      <div className={`max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 items-center`}>
        <div className="flex items-center justify-between h-14 lg:h-16">
          <a href="/" className={`flex items-center gap-2`} aria-label="Home">
            {logo ? <img src={logo} alt={brand} className="h-7 w-auto" /> : null}
            <span className="text-lg font-semibold tracking-tight text-text">{brand}</span>
          </a>
          <div className={`hidden md:flex items-center gap-8`}>
            {navLinks.map((link) => (
              <a key={link.href} href={link.href} className="text-sm font-medium text-text-secondary hover:text-text transition-colors duration-200">
                {link.label}
              </a>
            ))}
            {ctaButton && (
              <a href={ctaLink} className={`inline-flex items-center px-5 py-2.5 text-sm font-semibold text-white bg-wae-gradient-primary rounded-xl hover:opacity-95 transition-all duration-200 shadow-lift focus:outline-none focus:ring-2 focus:ring-primary focus:ring-offset-2`}>
                {ctaText}
              </a>
            )}
            
          </div>
          <button
            type="button"
            onClick={() => setMobileOpen(!mobileOpen)}
            className="md:hidden inline-flex items-center justify-center p-2 rounded-lg text-text-secondary hover:text-secondary hover:bg-surface focus:outline-none focus:ring-2 focus:ring-primary"
            aria-label={mobileOpen ? "Close main menu" : "Open main menu"}
            aria-expanded={mobileOpen}
          >
            {mobileOpen ? (
              <svg className="w-6 h-6" fill="none" viewBox="0 0 24 24" stroke="currentColor" aria-hidden="true">
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M6 18L18 6M6 6l12 12" />
              </svg>
            ) : (
              <svg className="w-6 h-6" fill="none" viewBox="0 0 24 24" stroke="currentColor" aria-hidden="true">
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M4 6h16M4 12h16M4 18h16" />
              </svg>
            )}
          </button>
        </div>
      </div>
      
      {mobileOpen && (
        <div className="md:hidden border-t border-text-secondary/15 bg-surface">
          <div className="px-4 py-4 space-y-1">
            {navLinks.map((link) => (
              <a
                key={link.href}
                href={link.href}
                onClick={() => setMobileOpen(false)}
                className="block px-3 py-2.5 rounded-lg text-base font-medium text-secondary hover:text-secondary hover:bg-background transition-colors duration-200"
              >
                {link.label}
              </a>
            ))}
            {ctaButton && (
              <a
                href={ctaLink}
                onClick={() => setMobileOpen(false)}
                className="mt-2 block text-center px-5 py-2.5 text-sm font-semibold text-white bg-wae-gradient-primary rounded-xl hover:opacity-95 transition-all duration-200 shadow-lift"
              >
                {ctaText}
              </a>
            )}
          </div>
        </div>
      )}
    </nav>
  );
}
