// Auto-generated by WAE — Nimbus
// Component: page-header (default)

export default function PageHeader({
  title = "Contact",
  subtitle = "",
  align = "center",
}: {
  title?: string;
  subtitle?: string;
  align?: string;
}) {
  return (
    <section className="py-16 sm:py-20 bg-surface border-b border-text-secondary/15" aria-label="Page heading">
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
        <div className={`max-w-3xl mx-auto text-center`}>
          <h1 className="text-4xl sm:text-5xl font-bold tracking-tight text-secondary">{title}</h1>
          {subtitle ? (
            <p className="mt-4 text-lg text-text-secondary leading-relaxed">{subtitle}</p>
          ) : null}
        </div>
      </div>
    </section>
  );
}
