// Auto-generated by WAE — Nimbus
// Component: pricing-table (3-tier)

export default function PricingTable({
  tiers = 3,
  highlightedTier = "middle",
  showFeatures = true,
  billing = "monthly",
  headline = "Simple, Transparent Pricing",
  subtitle = "Choose the plan that fits your needs.",
  pricing = [{"name":"Starter","price":"$0","description":"For trying Nimbus with your own documents.","features":["200 pages / month","Extract + Summarize","Community support"]},{"name":"Growth","price":"$99","description":"For teams that need reliable volume.","features":["10,000 pages / month","All modules","Priority support"]},{"name":"Enterprise","price":"Custom","description":"For scale, security and control.","features":["Unlimited pages","SOC 2 + SSO/SAML","Dedicated manager"]}],
  plans = [{"name":"Starter","price":"$0","description":"For trying Nimbus with your own documents.","features":["200 pages / month","Extract + Summarize","Community support"]},{"name":"Growth","price":"$99","description":"For teams that need reliable volume.","features":["10,000 pages / month","All modules","Priority support"]},{"name":"Enterprise","price":"Custom","description":"For scale, security and control.","features":["Unlimited pages","SOC 2 + SSO/SAML","Dedicated manager"]}],
}: {
  tiers?: number;
  highlightedTier?: string;
  showFeatures?: boolean;
  billing?: string;
  headline?: string;
  subtitle?: string;
  pricing?: Array<{ name: string; price: string; description: string; features: string[]; highlighted?: boolean; period?: string; cta?: string }>;
  plans?: Array<{ name: string; price: string; description: string; features: string[]; highlighted?: boolean; period?: string; cta?: string }>;
}) {
  const isHighlighted = (index: number) => {
    if (highlightedTier === 'first') return index === 0;
    if (highlightedTier === 'last') return index === plans.length - 1;
    if (highlightedTier === 'middle') return index === Math.floor(plans.length / 2);
    return false;
  };

  return (
    <section className="container mx-auto px-4 py-12">
      <div className="text-center mb-12">
        <h2 className="text-3xl font-bold tracking-tight sm:text-4xl">{headline}</h2>
        <p className="mt-4 text-lg text-text-secondary dark:text-text-secondary max-w-2xl mx-auto">{subtitle}</p>
      </div>
      <div className="grid gap-8 lg:grid-cols-3">
        {plans.slice(0, tiers).map((plan, index) => (
          <div
            key={index}
            className={
              'relative flex flex-col rounded-2xl border p-8 shadow-sm ' +
              (isHighlighted(index)
                ? 'border-accent ring-2 ring-indigo-600 scale-105'
                : 'border-text-secondary/15 dark:border-gray-700')
            }
          >
            {isHighlighted(index) && (
              <span className="absolute -top-3 left-1/2 -translate-x-1/2 rounded-full bg-accent px-3 py-1 text-xs font-semibold text-white">
                Most Popular
              </span>
            )}
            <div className="mb-6">
              <h3 className="text-xl font-semibold text-secondary">{plan.name}</h3>
              <p className="mt-2 text-sm text-text-secondary dark:text-text-secondary">{plan.description}</p>
            </div>
            <div className="mb-6">
              <span className="text-4xl font-bold text-secondary">{plan.price}</span>
              <span className="text-sm text-text-secondary dark:text-text-secondary">/{billing}</span>
            </div>
            {showFeatures && plan.features && (
              <ul className="mb-8 space-y-3 flex-1">
                {plan.features.map((feature, fIndex) => (
                  <li key={fIndex} className="flex items-start gap-2 text-sm text-text-secondary dark:text-text-secondary">
                    <svg className="h-5 w-5 flex-shrink-0 text-accent mt-0.5" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                      <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M5 13l4 4L19 7" />
                    </svg>
                    {feature}
                  </li>
                ))}
              </ul>
            )}
            <button
              className={
                'mt-auto w-full rounded-lg px-4 py-2.5 text-sm font-semibold transition-colors ' +
                (isHighlighted(index)
                  ? 'bg-accent text-white hover:opacity-90'
                  : 'bg-surface text-secondary hover:bg-surface hover:opacity-80')
              }
            >
              Choose {plan.name}
            </button>
          </div>
        ))}
      </div>
    </section>
  );
}