// Auto-generated by WAE — Nimbus
// Component: visual-background (default)
// Renders the generic Visual Capability renderer (abstract capability →
// provider → fallback). The capability is an ABSTRACT name — never a library.
// Extra props from project.yaml are accepted and ignored (structural slot).

import VisualCapability from "@/components/visual-capability";

export default function VisualBackground({
  capabilities = [],
}: {
  capabilities?: string[];
  [key: string]: unknown;
}) {
  const capability = Array.isArray(capabilities) && capabilities.length > 0 ? capabilities[0] : "";
  return <VisualCapability capability={capability} />;
}
