// Auto-generated by WAE — generic Visual Capability renderer.
// This component is generated from the Visual Capability Registry. It only
// knows ABSTRACT capabilities and provider ids — it never hardcodes a
// library. The provider components live in src/components/visual/ and are
// lazy-loaded client chunks (WebGL) or static fallbacks (SSR-safe).

"use client";

import { useEffect, useState } from "react";

// Deterministic provider chains resolved at generation time by the WAE Visual
// Capability Resolver. Each link: { provider, webgl, props }.
const CAPABILITIES: Record<string, Array<{ provider: string; webgl: boolean; props: Record<string, unknown> }>> = {
  "procedural-background": [{"provider":"css-gradient","webgl":false,"props":{"animated":false,"colors":{"primary":"#4f46e5","secondary":"#6366f1","accent":"#818cf8","background":"#ffffff"}}}],
  "image-preview": [{"provider":"image","webgl":false,"props":{"colors":{"primary":"#4f46e5","secondary":"#6366f1","accent":"#818cf8","background":"#ffffff"}}}],
  "shader-background": [{"provider":"shadergradient","webgl":true,"props":{"speed":0.35,"grain":"off","type":"plane","animate":"on","colors":{"primary":"#4f46e5","secondary":"#6366f1","accent":"#818cf8","background":"#ffffff"},"spec":{"visualMood":"technical","motionLevel":"static","depthLevel":"flat","colorStrategy":"brand-palette","density":"high","intensity":"subtle","cameraStyle":"fixed","surfaceType":"plane","grain":"off","interaction":"none","performanceBudget":"medium"}}},{"provider":"webgl-gradient","webgl":true,"props":{"speed":0.35,"colors":{"primary":"#4f46e5","secondary":"#6366f1","accent":"#818cf8","background":"#ffffff"},"spec":{"visualMood":"technical","motionLevel":"static","depthLevel":"flat","colorStrategy":"brand-palette","density":"high","intensity":"subtle","cameraStyle":"fixed","surfaceType":"plane","grain":"off","interaction":"none","performanceBudget":"medium"}}},{"provider":"css-gradient","webgl":false,"props":{"animated":false,"colors":{"primary":"#4f46e5","secondary":"#6366f1","accent":"#818cf8","background":"#ffffff"},"spec":{"visualMood":"technical","motionLevel":"static","depthLevel":"flat","colorStrategy":"brand-palette","density":"high","intensity":"subtle","cameraStyle":"fixed","surfaceType":"plane","grain":"off","interaction":"none","performanceBudget":"medium"}}}]
};

function detectWebGL(): boolean {
  if (typeof window === "undefined") return false;
  try {
    const canvas = document.createElement("canvas");
    return Boolean(
      window.WebGLRenderingContext &&
        (canvas.getContext("webgl2") || canvas.getContext("webgl")),
    );
  } catch {
    return false;
  }
}

function prefersReducedMotion(): boolean {
  if (typeof window === "undefined") return false;
  try {
    return window.matchMedia("(prefers-reduced-motion: reduce)").matches;
  } catch {
    return false;
  }
}

function detectMobile(): boolean {
  if (typeof window === "undefined") return false;
  try {
    return (
      window.matchMedia("(max-width: 767px)").matches ||
      (typeof navigator !== "undefined" && navigator.maxTouchPoints > 0 && window.innerWidth < 768)
    );
  } catch {
    return false;
  }
}

async function loadProvider(provider: string) {
  switch (provider) {
    case "shadergradient":
      return (await import("./visual/shadergradient-provider")).default;
    case "webgl-gradient":
      return (await import("./visual/webgl-gradient-provider")).default;
    case "css-gradient":
      return (await import("./visual/css-gradient-provider")).default;
    case "image":
      return (await import("./visual/image-provider")).default;
    default:
      return null;
  }
}

// Static providers are safe to render during SSR and on first paint
// (progressive enhancement: static gradient -> animated gradient).
function StaticFallback({ link }: { link: { provider: string; props: Record<string, unknown> } }) {
  const props = link.props as { colors?: Record<string, string>; logo?: { src?: string; alt?: string }; image?: { src?: string; alt?: string } };
  if (link.provider === "static-logo" && props.logo?.src) {
    return <img src={props.logo.src} alt={props.logo.alt ?? ""} className="mx-auto h-24 w-auto opacity-90" />;
  }
  if (link.provider === "image" && props.image?.src) {
    return <img src={props.image.src} alt={props.image.alt ?? ""} className="h-full w-full object-cover" />;
  }
  const colors = props.colors ?? {};
  const primary = colors.primary ?? "#6366f1";
  const secondary = colors.secondary ?? "#a855f7";
  return (
    <div
      className="h-full w-full"
      style={{
        background:
          "linear-gradient(135deg, " +
          primary +
          " 0%, " +
          secondary +
          " 100%)",
      }}
    />
  );
}

export default function VisualCapability({
  capability,
  variant = "fixed",
  props: overrides = {},
}: {
  capability?: string;
  variant?: "fixed" | "contained";
  props?: Record<string, unknown>;
}) {
  const spec = CAPABILITIES[capability ?? ""] ?? CAPABILITIES[Object.keys(CAPABILITIES)[0]];
  if (!spec || spec.length === 0) return null;

  // Merge per-use overrides (e.g. per-project image/colors) over the resolved
  // defaults so the renderer stays generic and fully data-driven.
  const mergeProps = (base: Record<string, unknown>) => {
    const merged: Record<string, unknown> = { ...base };
    const baseImg = (base.image ?? {}) as Record<string, unknown>;
    const overrideImg = (overrides.image ?? {}) as Record<string, unknown>;
    if (overrides.image) merged.image = { ...baseImg, ...overrideImg };
    const baseColors = (base.colors ?? {}) as Record<string, unknown>;
    const overrideColors = (overrides.colors ?? {}) as Record<string, unknown>;
    if (overrides.colors) merged.colors = { ...baseColors, ...overrideColors };
    if (overrides.logo) merged.logo = { ...(base.logo as Record<string, unknown>), ...(overrides.logo as Record<string, unknown>) };
    return merged;
  };

  // SSR + first paint: deterministic static fallback (final chain link,
  // always non-WebGL).
  const ssrLink = spec[spec.length - 1];
  const [Active, setActive] = useState<React.ComponentType<Record<string, unknown>> | null>(null);
  const [linkIndex, setLinkIndex] = useState(spec.length - 1);

  useEffect(() => {
    let cancelled = false;
    const webgl = detectWebGL();
    const reduced = prefersReducedMotion();
    const mobile = detectMobile();

    const firstNonWebgl = spec.findIndex((l) => !l.webgl);
    const startIndex = (() => {
      // Reduced motion or constrained mobile devices prefer the lightweight
      // non-WebGL provider; otherwise WebGL providers run when available.
      if (reduced || mobile) return firstNonWebgl >= 0 ? firstNonWebgl : spec.length - 1;
      if (webgl) return 0;
      return firstNonWebgl >= 0 ? firstNonWebgl : spec.length - 1;
    })();

    const tryLoad = async (index: number) => {
      if (cancelled) return;
      const link = spec[index];
      if (!link) return;
      try {
        const component = await loadProvider(link.provider);
        if (component && !cancelled) {
          setActive(() => component as React.ComponentType<Record<string, unknown>>);
          setLinkIndex(index);
          return;
        }
      } catch {
        // Provider failed to load (e.g. import error) — fall back down the
        // deterministic chain. Generation never fails; the static fallback
        // always exists.
      }
      const next = index + 1;
      if (next < spec.length) await tryLoad(next);
    };

    // One frame delay: let the static fallback paint before the heavy WebGL
    // provider loads (no flash, graceful upgrade).
    const raf = requestAnimationFrame(() => {
      void tryLoad(startIndex);
    });
    return () => {
      cancelled = true;
      cancelAnimationFrame(raf);
    };
  }, [spec]);

  const current = spec[linkIndex] ?? spec[spec.length - 1];
  const containerClass =
    variant === "contained"
      ? "absolute inset-0 overflow-hidden pointer-events-none"
      : "fixed inset-0 z-0 overflow-hidden pointer-events-none";
  return (
    <div className={containerClass} aria-hidden="true">
      {Active ? <Active {...mergeProps(current.props)} /> : <StaticFallback link={{ provider: ssrLink.provider, props: mergeProps(ssrLink.props) }} />}
    </div>
  );
}
