// Auto-generated by WAE — CSS gradient provider (static fallback).
// No WebGL, SSR-safe, reduced-motion safe by design (static, not animated).
export default function CssGradientProvider({
  colors,
}: {
  colors?: Record<string, string>;
}) {
  const primary = colors?.primary ?? "#6366f1";
  const secondary = colors?.secondary ?? "#a855f7";
  const accent = colors?.accent ?? "#22d3ee";
  return (
    <div
      className="h-full w-full"
      style={{
        background:
          "radial-gradient(1200px 700px at 20% 10%, " +
          primary +
          " 0%, transparent 60%)," +
          "radial-gradient(1000px 600px at 85% 90%, " +
          accent +
          " 0%, transparent 55%)," +
          "linear-gradient(135deg, " +
          primary +
          " 0%, " +
          secondary +
          " 100%)",
      }}
    />
  );
}
