// Auto-generated by WAE — image provider (static fallback).
export default function ImageProvider({
  image,
}: {
  image?: { src?: string; alt?: string };
}) {
  if (!image?.src) return null;
  return <img src={image.src} alt={image.alt ?? ""} className="h-full w-full object-cover" />;
}
