// Auto-generated by WAE — ShaderGradient provider.
// Isolated behind the Visual Capability interface. Client-only, WebGL.
// The WAE ShaderBackgroundSpec is translated to ShaderGradient parameters
// HERE — the only place the ShaderGradient API is known. Deterministic.
"use client";

import { ShaderGradientCanvas, ShaderGradient } from "@shadergradient/react";

// WAE ShaderBackgroundSpec → ShaderGradient params (deterministic adapter).
// No runtime randomness; identical spec always produces identical params.
// The 'any' return type keeps the provider generic and build-safe under strict
// TS while the spec remains a committed, deterministic WAE contract. Note:
// this generated code must stay free of raw backticks (template literal host).
function adaptSpec(spec: Record<string, any> | undefined): any {
  if (!spec) return {};
  const speed: Record<string, number> = { static: 0.15, drift: 0.35, cinematic: 0.6 };
  const strength: Record<string, number> = { subtle: 1.5, medium: 3, strong: 5 };
  const density: Record<string, number> = { low: 3, medium: 5.5, high: 9 };
  const distance: Record<string, number> = { flat: 3, dimensional: 4, deep: 5.5 };
  const polar: Record<string, number> = { flat: 90, dimensional: 90, deep: 60 };
  const pixel: Record<string, number> = { low: 1, medium: 1.5, high: 1.5 };
  const motionLevel = spec.motionLevel ?? "drift";
  const densityLevel = spec.density ?? "medium";
  const intensity = spec.intensity ?? "medium";
  const depthLevel = spec.depthLevel ?? "dimensional";
  const grain = spec.grain ?? "off";
  return {
    type: spec.surfaceType ?? "plane",
    animate: motionLevel === "static" ? "off" : "on",
    uSpeed: speed[motionLevel],
    uStrength: strength[intensity],
    uDensity: density[densityLevel],
    uFrequency: density[densityLevel],
    cDistance: distance[depthLevel],
    cPolarAngle: polar[depthLevel],
    cAzimuthAngle: motionLevel === "cinematic" ? 150 : 90,
    grain: grain === "off" ? "off" : "on",
    pixelDensity: pixel[spec.performanceBudget ?? "medium"],
  };
}

export default function ShaderGradientProvider({
  colors,
  speed = 0.35,
  spec,
}: {
  colors?: Record<string, string>;
  speed?: number;
  spec?: Record<string, string | number>;
}) {
  const primary = colors?.primary ?? "#6366f1";
  const secondary = colors?.secondary ?? "#a855f7";
  const accent = colors?.accent ?? "#22d3ee";
  const p = adaptSpec(spec);
  return (
    <ShaderGradientCanvas style={{ position: "absolute", inset: 0 }} pixelDensity={p.pixelDensity ?? 1} fov={45}>
      <ShaderGradient
        type={p.type ?? "plane"}
        animate={p.animate ?? "on"}
        uSpeed={p.uSpeed ?? speed}
        uStrength={p.uStrength ?? 3}
        uDensity={p.uDensity ?? 5.5}
        uFrequency={p.uFrequency ?? 5.5}
        cDistance={p.cDistance ?? 4}
        cPolarAngle={p.cPolarAngle ?? 90}
        cAzimuthAngle={p.cAzimuthAngle ?? 90}
        grain={p.grain ?? "off"}
        color1={primary}
        color2={secondary}
        color3={accent}
      />
    </ShaderGradientCanvas>
  );
}
