// Auto-generated by WAE — WebGL Gradient provider (self-contained GLSL).
// A subtle, premium animated gradient field. No external dependencies —
// works on every React version. Falls back to the CSS gradient provider
// automatically when WebGL is unavailable.
"use client";

import { useEffect, useRef } from "react";

const VERT = `
attribute vec2 aPosition;
void main() {
  gl_Position = vec4(aPosition, 0.0, 1.0);
}
`;

const FRAG = `
precision highp float;
uniform vec2 uResolution;
uniform float uTime;
uniform vec3 uPrimary;
uniform vec3 uSecondary;
uniform vec3 uAccent;
uniform vec3 uBackground;

vec2 drift(vec2 base, float t, float a, float b) {
  return vec2(base.x + 0.10 * sin(t * a), base.y + 0.10 * cos(t * b));
}

void main() {
  vec2 uv = gl_FragCoord.xy / uResolution.xy;
  float aspect = uResolution.x / uResolution.y;
  float t = uTime * 0.05;
  vec2 p = (uv - 0.5) * vec2(aspect, 1.0);

  vec2 c1 = drift(vec2(-0.42, -0.30), t, 0.80, 0.90);
  vec2 c2 = drift(vec2(0.46, 0.34), t, 0.70, 0.60);
  vec2 c3 = drift(vec2(0.05, -0.05), t, 0.55, 0.72);

  float d1 = 1.0 - smoothstep(0.0, 1.10, length(p - c1));
  float d2 = 1.0 - smoothstep(0.0, 1.25, length(p - c2));
  float d3 = 1.0 - smoothstep(0.0, 0.95, length(p - c3));

  vec3 col = uBackground;
  col = mix(col, uPrimary, d1 * 0.85);
  col = mix(col, uSecondary, d2 * 0.70);
  col = mix(col, uAccent, d3 * 0.50);
  col += 0.015 * vec3(
    sin(p.y * 3.0 + t * 4.0),
    cos(p.x * 3.0 - t * 4.0),
    sin((p.x + p.y) * 3.0 + t * 2.0)
  );
  gl_FragColor = vec4(col, 1.0);
}
`;

function hexToRgb(hex: string): [number, number, number] {
  const value = hex.replace("#", "");
  const int = parseInt(value.length === 3 ? value.split("").map((c) => c + c).join("") : value, 16);
  return [((int >> 16) & 255) / 255, ((int >> 8) & 255) / 255, (int & 255) / 255];
}
export default function WebglGradientProvider({
  colors = {},
  speed = 0.35,
}: {
  colors?: Record<string, string>;
  speed?: number;
}) {
  const canvasRef = useRef<HTMLCanvasElement | null>(null);

  useEffect(() => {
    const canvas = canvasRef.current;
    if (!canvas) return;
    const gl = canvas.getContext("webgl2") || canvas.getContext("webgl");
    if (!gl) return; // renderer falls back to the CSS gradient provider

    const primary = hexToRgb(colors.primary ?? "#6366f1");
    const secondary = hexToRgb(colors.secondary ?? "#a855f7");
    const accent = hexToRgb(colors.accent ?? "#22d3ee");
    const background = hexToRgb(colors.background ?? "#0f172a");

    const compile = (type: number, source: string) => {
      const shader = gl.createShader(type)!;
      gl.shaderSource(shader, source);
      gl.compileShader(shader);
      return shader;
    };
    const program = gl.createProgram()!;
    gl.attachShader(program, compile(gl.VERTEX_SHADER, VERT));
    gl.attachShader(program, compile(gl.FRAGMENT_SHADER, FRAG));
    gl.linkProgram(program);
    if (!gl.getProgramParameter(program, gl.LINK_STATUS)) return;
    gl.useProgram(program);

    const buffer = gl.createBuffer();
    gl.bindBuffer(gl.ARRAY_BUFFER, buffer);
    gl.bufferData(gl.ARRAY_BUFFER, new Float32Array([-1, -1, 1, -1, -1, 1, 1, 1]), gl.STATIC_DRAW);
    const aPosition = gl.getAttribLocation(program, "aPosition");
    gl.enableVertexAttribArray(aPosition);
    gl.vertexAttribPointer(aPosition, 2, gl.FLOAT, false, 0, 0);

    const uResolution = gl.getUniformLocation(program, "uResolution");
    const uTime = gl.getUniformLocation(program, "uTime");
    const uPrimary = gl.getUniformLocation(program, "uPrimary");
    const uSecondary = gl.getUniformLocation(program, "uSecondary");
    const uAccent = gl.getUniformLocation(program, "uAccent");
    const uBackground = gl.getUniformLocation(program, "uBackground");

    let raf = 0;
    let running = true;
    let start = performance.now();

    const resize = () => {
      const rect = canvas.getBoundingClientRect();
      const dpr = Math.min(window.devicePixelRatio || 1, 2);
      canvas.width = Math.max(1, Math.round(rect.width * dpr));
      canvas.height = Math.max(1, Math.round(rect.height * dpr));
      gl.viewport(0, 0, canvas.width, canvas.height);
    };

    const render = (now: number) => {
      if (!running) return;
      const t = ((now - start) / 1000) * speed;
      gl.uniform2f(uResolution, canvas.width, canvas.height);
      gl.uniform1f(uTime, t);
      gl.uniform3f(uPrimary, primary[0], primary[1], primary[2]);
      gl.uniform3f(uSecondary, secondary[0], secondary[1], secondary[2]);
      gl.uniform3f(uAccent, accent[0], accent[1], accent[2]);
      gl.uniform3f(uBackground, background[0], background[1], background[2]);
      gl.drawArrays(gl.TRIANGLE_STRIP, 0, 4);
    };

    const frame = (now: number) => {
      render(now);
      if (running) raf = requestAnimationFrame(frame);
    };

    resize();
    window.addEventListener("resize", resize);

    // Respect prefers-reduced-motion: render one static frame and stop.
    let reduced = false;
    try {
      reduced = window.matchMedia("(prefers-reduced-motion: reduce)").matches;
    } catch {
      /* ignore */
    }
    if (reduced) {
      render(performance.now());
    } else {
      raf = requestAnimationFrame(frame);
    }

    return () => {
      running = false;
      cancelAnimationFrame(raf);
      window.removeEventListener("resize", resize);
      try {
        gl.getExtension("WEBGL_lose_context")?.loseContext();
      } catch {
        /* ignore */
      }
    };
  }, [colors.primary, colors.secondary, colors.accent, colors.background, speed]);

  return <canvas ref={canvasRef} className="h-full w-full" aria-hidden="true" />;
}
